version: '3.2'
services:
  backend-swoole:
    container_name: api-swoole
    build:
      context: .
    restart: unless-stopped
    tty: true
    ports:
      - "6000:5000"
    volumes:
      - ./api:/app
    networks:
      - api-network

# Here we specify our networks
networks:
  api-network:
    driver: bridge

    